spring.application.name=gestion_exams

######################################
#   CONFIGURATION SERVEUR - TEST
######################################
server.port=8081
server.servlet.context-path=/api/v1

######################################
#   CONFIGURATION BASE DE DONNEES
######################################
# URL JDBC pour MySQL
spring.datasource.url=jdbc:mysql://localhost:3316/gestion_examens
spring.datasource.username=root
spring.datasource.password=passwd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

######################################
#   CONFIGURATION JPA/HIBERNATE TEST
######################################
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=30

logging.level.org.springframework.context=DEBUG
logging.level.org.springframework.beans=DEBUG
logging.level.org.springframework.security=DEBUG
server.error.include-binding-errors=always
server.error.include-message=always
